services:
  rsshub:
    image: diygod/rsshub
    container_name: rsshub
    restart: unless-stopped
    environment:
      NODE_ENV: production
      CACHE_TYPE: redis
      REDIS_URL: 'redis://redis:6379/'
    env_file:
      - env
    depends_on:
      - redis
    labels:
      - com.centurylinklabs.watchtower.enable=true

  redis:
    image: 'redis:alpine'
    restart: unless-stopped
    volumes:
      - 'redis-data:/data'

  cloudflared:
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run rsshub
    env_file:
      - env
    labels:
      - com.centurylinklabs.watchtower.enable=true

volumes:
  redis-data:
