name: galerie
services:
  galerie:
    image: ghcr.io/sekai-soft/galerie:latest
    container_name: galerie
    restart: unless-stopped
    environment:
      POCKET_CONSUMER_KEY: 'YOUR_CONSUMER_KEY'
      BASE_URL: 'https://galerie-reader.app'
  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      TUNNEL_TOKEN: 'YOUR_TUNNEL_TOKEN'
